### ISSUE TITLE
Timeline element won't alternate align the items

### ISSUE THREAD

**Issue by IrinaGhi** [forrestkirby/timeline-element#11]
Hi, I can't make the element alternately align the items, it just aligns them all left and won't show any vertical line. Do I have to make any extra setting in the Yootheme builder for it to work? like load jquery or something? 
Thank you!

**Comment by forrestkirby** [comment]
Hi IrinaGhi,

This sounds like the CSS is not loaded on your website. Are both YOOtheme Pro and the timeline element up to date on your website? Can you share a link to your website?

> Do I have to make any extra setting in the Yootheme builder for it to work? like load jquery or something?

No, the line should always show up and the alignment can be configured in the element settings. jQuery is not required.

Kind regards
Thomas

**Comment by IrinaGhi** [comment]
Yes, updating yootheme solved it, thanks a lot!
