### ISSUE TITLE
Set Timeline Element in yootheme

### ISSUE THREAD

**Issue by fvdn** [forrestkirby/timeline-element#12]
Hi,

I would like to set your yootheme timeline element so that the timeline is in the middle and the content is on both left and right (just like your example on github). I cannot manage to do this now (everything will be placed on the right). How do I do this.

**Comment by forrestkirby** [comment]
Hi fvdn,

that’s what the options in the field group *Item Alignment* in the *Settings* of the element are for.

![](https://content.screencast.com/users/forrestkirby/folders/YOOtheme/media/ec4f930c-4d5d-41db-bf13-fd37676b75c9/01.20.2021-07.34.png)

By default, the item alignment should be on the right up to the medium breakpoint and for bigger screens it should be left alternate, that is the timeline in the middle and the items left, right, left, right…

Also see [this screencast](https://www.screencast.com/t/1HbyXRmp).

If that’s not the case on your website, check that YOOtheme Pro and the Timeline Element are up to date. Also make sure that there’s no error in your HTML markup and all resources are correctly loaded.

Best regards

**Comment by forrestkirby** [comment]
closed due to inactivity
