### ISSUE TITLE
Call to undefined function YOOtheme\app() in YOOtheme Pro 1.22.8 for Wordpress

### ISSUE THREAD

**Issue by forrestkirby** [forrestkirby/timeline-element#4]
from #1

> Hello forrestkirby,
Wordpress, YOOtheme Version 1.22.8
maybe you can help me?
I have already tried both versions and the error comes again:

```
Fatal error: Uncaught Error: Call to undefined function YOOtheme\app() in /www/htdocs/xxx.de/wp-content/themes/yootheme-child/builder/hd-timeline/element.php:14 Stack trace: #0 /www/htdocs/xxx.de/wp-content/themes/yootheme/vendor/yootheme/builder/src/Builder.php(275): YOOtheme\ConfigManager->YOOtheme{closure}(Object(stdClass), Array) #1 /www/htdocs/xxx.de/wp-content/themes/yootheme/vendor/yootheme/builder/src/Builder.php(260): YOOtheme\Builder->applyTransforms(Object(stdClass), Array) #2 /www/htdocs/xxx.de/wp-content/themes/yootheme/vendor/yootheme/builder/src/Builder.php(260): YOOtheme\Builder->applyTransforms(Object(stdClass), Array) #3 /www/htdocs/xxx.de/wp-content/themes/yootheme/vendor/yootheme/builder/src/Builder.php(260): YOOtheme\Builder->applyTransforms(Object(stdClass), Array) #4 /www/htdocs/xxx.de/wp-content/themes/yootheme/vendor/yootheme/builder/src/Builder.php(260): in /www/htdocs/xxx.de/wp-content/themes/yootheme-child/builder/hd-timeline/element.php on line 14
```

> Regards
Max

**Comment by forrestkirby** [comment]
Hi Max,

the current version is already built for YOOtheme Pro 2.0 (see the [changelog](https://github.com/forrestkirby/timeline-element/blob/master/CHANGELOG.md)). Please try [this package (1.3)](https://github.com/forrestkirby/timeline-element/archive/c7df37e266dbbc3e3f441750f90ef774e6de7ee2.zip) instead. [Repository at that point in the history](https://github.com/forrestkirby/timeline-element/tree/c7df37e266dbbc3e3f441750f90ef774e6de7ee2)

Regards
Thomas

**Comment by hennesohg** [comment]
Hi Thomas,
thank you very much for the help, it works now!
Best regards
