### ISSUE TITLE
cannot add new timeline or element

### ISSUE THREAD

**Issue by webgras** [forrestkirby/timeline-element#6]
Just installed the latest 2.0.0-beta.10
But I cannot add a new timeline element or a new timeline item. If I click, nothing happens...
I am using Joomla 3.9 and Yootheme 2.1.1

**Comment by forrestkirby** [comment]
Hi webgras,

the latest version of the Timeline Element is 2.1.0-beta.1 (i.e. the current master branch) which is compatible with YOOtheme Pro 2.1.1. Please update the timeline element.

Note: Generally speaking, I recommend to update in this order:

1. custom elements (by replacing the files via FTP or delete the old files, then upload the new files)
2. YOOtheme Pro (by 1-click updates)

Regards
Thomas
